---
title: "Untitled"
author: "Dorothee Mersch"
date: "18 Juli 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 5. Linear Regression: 
## Is it possible to predict our IC50 values?


```{r, echo=FALSE}
library(ggplot2)
```
```{r, echo=FALSE}
results = readRDS("C:/Users/Dori/Desktop/Studium/SS_19/Bioinfo Projekt/GitHub/project-02-group-02#project-02-group-02/data/results.rds")
drug_activity_rges <- readRDS("C:/Users/Dori/Desktop/Studium/SS_19/Bioinfo Projekt/GitHub/project-02-group-02#project-02-group-02/data/drug_activity_rges.rds")
```
```{r, echo=FALSE}
# limit the data set to numerical values
rges.ic50 <- as.data.frame(drug_activity_rges[,c(2,9)])
```

### Do our RGES also positively correlate to IC50?
Bad Correlation &rarr; Bad Linear Regression Model
```{r,echo=FALSE, include=TRUE}
ggplot(rges.ic50, aes(rges.ic50$RGES, rges.ic50$IC50.value)) +
  geom_point(color = "blue", size = 1) +
  scale_size(range = c(2,5)) +
  xlab("RGES") + 
  ylab("IC50") 
```

### How can the model be enhanced?

**+  Previously found 15 biomarkers for cisplatin**
  

```{r, echo=FALSE}
#Multiple Regression
# Include biomarkers to RGES matrix only for cisplatin!
double.biomarker.FC <- readRDS("C:/Users/Dori/Desktop/Studium/SS_19/Bioinfo Projekt/GitHub/project-02-group-02#project-02-group-02/data/double.biomarker.FC.rds")
drug_activity_rges.cisplatin = subset (drug_activity_rges , drug == "cisplatin")
# transformieren, damit samples in zeile
biomarker.FC = t(double.biomarker.FC)

# fit both matrices
biomarker.FC.fit = subset(biomarker.FC, rownames(biomarker.FC) %in% drug_activity_rges.cisplatin$sample)

# limit the data set to numerical values: rges, ic50 and biomarkers:
rges.ic50.biomarkers <- as.data.frame(cbind(drug_activity_rges.cisplatin[,c(2,9)], biomarker.FC.fit))
```
```{r, echo=FALSE, include=TRUE, fig.align="center"}
cor.mat = cor(rges.ic50.biomarkers, method = "spearman")
heatmap(cor.mat, col = cm.colors(256), main = "Heatmap Correlation RGES, IC50, Biomarkers", symm = T)
```

#### Computation of the Model
```{r, echo = FALSE, include=FALSE}
train.multiple = sample(1:nrow(rges.ic50.biomarkers), 45)
 
train.set.multiple = rges.ic50.biomarkers[train.multiple, ]
test.set.multiple = rges.ic50.biomarkers[-train.multiple, ]
```
```{r, echo=TRUE, include=TRUE}
model.multiple = lm(IC50.value ~ ., data = train.set.multiple)
```
```{r, echo=FALSE, include=FALSE}
R.squared <- summary(model.multiple)$adj.r.squared
F.statistic <- summary(model.multiple)$fstatistic[1]
P.values <- summary(model.multiple)$coefficients[,4]
```
```{r, echo = FALSE, include=FALSE}
predict.multiple = predict(model.multiple, newdata = test.set.multiple)
```
```{r, echo=FALSE}
n = nrow(test.set.multiple)
residuals = test.set.multiple$IC50.value - predict.multiple
RMSE = sqrt(1/n * sum(residuals^2))
results.model.multiple <- cbind(R.squared, F.statistic, RMSE)
```

```{r results = 'asis', echo=FALSE, include=TRUE}
knitr::kable(results.model.multiple, caption = "Results Multiple Regression Model")
```

#### Problem: High p values for coefficients:
```{r results = 'asis', echo=FALSE, include=TRUE} 
knitr::kable(P.values, caption = "P-values for coefficients")
```

### Computation of a model with selected variables: PTPRG, COMMD10, GMDS, LRBA
```{r, echo=TRUE, include=FALSE}
model.multiple.biomarkers = lm(IC50.value ~ PTPRG + COMMD10 + GMDS + LRBA, data = train.set.multiple)
``` 
```{r, echo=FALSE, include=FALSE}
R_squared <- summary(model.multiple.biomarkers)$adj.r.squared
F_statistic <- summary(model.multiple.biomarkers)$fstatistic[1]
```
```{r, echo = TRUE, include=FALSE}
predict.biomarkers = predict(model.multiple.biomarkers, newdata = test.set.multiple)
```
```{r, echo=FALSE}
n = nrow(test.set.multiple)
residuals = test.set.multiple$IC50.value - predict.biomarkers
rmse = sqrt(1/n * sum(residuals^2))
results.model.selected <- cbind(R_squared, F_statistic, rmse)
```
```{r results = 'asis', echo=FALSE, include=TRUE} 
knitr::kable(results.model.selected, caption = "P-values for coefficients")
```

```{r, echo=FALSE, include=TRUE}
plot(test.set.multiple$IC50.value, predict.biomarkers, xlab = "Real Values", ylab = "Predicted Values", pch=20, col="blue")
abline(0, 1, col = "red")
```